### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by PhilPJL** [ALMMa/datatables.aspnet#24]
Not sure if this is a problem with NuGet or datatables.aspnet.
One project in our solution of 101 projects uses DataTables.AspNet.Core and .Mvc5.  When using NuGet package manager in VS2015 for available upgrades, the pre-release version of DataTables shows up as an upgrade for all of them.
The filter is 'upgrade available'.  'include prerelease' is not checked.
This doesn't happen for any other nuget package.

**Comment by ALMMa** [comment]
Sounds like a NuGet extension error.

[From NuGet docs](https://docs.nuget.org/create/versioning):
> Note that the actual string applied doesn't matter. If there's a string there, it's a prerelease version.

With that in mind, anything after "2.0.0" will be treated as prerelease tag (for current version of Core, all the string "-beta1-102801"). Since you unchecked "Include Prerelease" box, NuGet should have filtered that out.

**Comment by ALMMa** [comment]
Closed: could not reproduce.

Tested multiple times with Visual Studio 2015 (14.0.24720.00 Update 1) along with latest Nuget extensions available at this time (20/jan/2016).
