### ISSUE TITLE
Asp.net Core RC2 support

### ISSUE THREAD

**Issue by sadjadbp** [ALMMa/datatables.aspnet#29]
Hi,

First thanks for the great project and your efforts. Do you have plans to support RC2? I've already got mine working. The only issue was ModelBinder.cs that I have to modify to accommodate RC2 changes.

**Comment by ALMMa** [comment]
Hello, @sadjadbp and thanks!

I'm already testing RC2 and new NuGet packages for DataTables.AspNet should be available soon, also with extension methods (currently available only through dev branch).

The reason it's not published yet is that I'm trying to rebuild tests from the ground-up so they become compatible with the new core framework :)

**Comment by sadjadbp** [comment]
even better, you are the man!

**Comment by LEsperanca** [comment]
Hi ALMMa, 
Do you have a date for the release compatible with RC2?

**Comment by ALMMa** [comment]
I'm reopening this issue since RC2 support is not yet finished.

I've just migrated source files to RC2 with a few renaming (eg: AspNet5 is now AspNetCore). I've also updated AspNetCore sample (basic integration) to make sure it's running correctly.

This should be ready for next week (June, 6~10). That's because I really need to rewrite test suite, fix a few issues reported so far and, most important, fully (and deeply) understand new .NET platform monikers so libs will ship with wider compatibility and better support for all platforms.

I should, however, provide a full commit of current work by tomorrow.

Now it's really up to you: should I release a NuGet package with partial RC2 support with this commit or should I wait a till next week with full test and better support?

**Comment by sadjadbp** [comment]
I'm in no rush

**Comment by vladislav-karamfilov** [comment]
Great news! Can't wait to see ASP.NET Core RC2 support. :)

**Comment by tedd** [comment]
Thanks! :) It would be great with an early commit for those of us that have moved the rest of the solution over to RC2 already. Better with something that compiles (even if buggy) than temporarily having to remove DT throghout solution. (Simple commit into dev branch would go a long way to solve problems.)

**Comment by rmarinho** [comment]
Di you pushed beta3 ? i was working on updating myself in my repo .

**Comment by ALMMa** [comment]
Yes. 
Beta 3 is still not complete but I've already pushed code so everyone can follow what's going on.

So far, main changes are related to AspNetCore and code compiling using RC2 and dotnet CLI.
I'm still working on tests (not ready yet) and samples, along with the migration path for legacy DataTables.Mvc and all.

Should take a couple of days to release Beta3 on NuGet. I still need to test everything before releasing those to the public. The only break should be for AspNetCore (renamed from AspNet5). Code should work just fine if you're already with Beta2.

**Comment by rmarinho** [comment]
Thanks @ALMMa i was talking about the packages .. saw the link in the readme.. i will reference the projects

**Comment by vladislav-karamfilov** [comment]
Any news on RC2 support? :)

**Comment by ALMMa** [comment]
Sorry for the delay. Had some trouble last week.
Beta3 is partially out. 

Core and implementation is working fine, and first part of the test suite is already done/fixed.
Need to finish extension methods and some tests. 
Should take a few more days to release every nuget package and update docs accordingly.

Important:
DataTables.AspNet.AspNet5 is now unlisted and deprecated due to renaming of the framework. Change it to DataTables.AspNet.AspNetCore. It starts on Beta3 to keep sync with other nuget packages.

Today's release works just fine, has been tested and should solve RC2 compatibility issues.
If you're running RC1, stick with Beta2. If you're on RC2, just move to Beta3. There should be no change on code.

Extensions will come firstly to ANSI-Sql and DapperExtensions.
After that, I'll be open to requests/suggestions.
Considering that I might have a very hard week ahead, this should be concluded by the end of june.

I'll keep this issue open untill Beta3 is fully out and docs are 100% ready.

**Comment by ALMMa** [comment]
Closed as .NET Core reached it's first stable/final version (1.0.0).
Check issue #32 for more info.
