### ISSUE TITLE
Doesn't work with MVC 5

### ISSUE THREAD

**Issue by TDK1964** [ALMMa/datatables.aspnet#37]
```
[MissingMethodException: Cannot create an instance of an interface.]
   System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck) +0
   System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +113
   System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark) +206
   System.Activator.CreateInstance(Type type, Boolean nonPublic) +83
   System.Activator.CreateInstance(Type type) +11
   System.Web.Mvc.DefaultModelBinder.CreateModel(ControllerContext controllerContext, ModelBindingContext bindingContext, Type modelType) +197
```

Also why is everything via the Url, seems very poor.
`/PageData?draw=1&columns%5B0%5D%5Bdata%5D=id&columns%5B0%5D%5Bname%5D=id&columns%5B0%5D%5Bsearchable%5D=false&columns%5B0%5D%5Borderable%5D=false&columns%5B0%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B0%5D%5Bsearch%5D%5Bregex%5D=false&columns%5B1%5D%5Bdata%5D=name&columns%5B1%5D%5Bname%5D=name&columns%5B1%5D%5Bsearchable%5D=false&columns%5B1%5D%5Borderable%5D=false&columns%5B1%5D%5Bsearch%5D%5Bvalue%5D=&columns%5B1%5D%5Bsearch%5D%5Bregex%5D=false&order%5B0%5D%5Bcolumn%5D=0&order%5B0%5D%5Bdir%5D=asc&start=0&length=10&search%5Bvalue%5D=&search%5Bregex%5D=false&_=1472740272535
`

**Comment by ALMMa** [comment]
## MissingMethodException
You cannot directly create an instance of an interface. That usually happens when MVC tries to activate the interface without the proper binding. 

Have you registered DataTables.AspNet bindings?

    // On global.asax, after RouteConfig, as shown on sample project:
    DataTables.AspNet.Mvc5.Configuration.RegisterDataTables();


## HTTP GET and query strings
About everything in the URL, that's how HTTP GET method works (query string) and is related to the request generation, which is client-side code and not server-side. From DataTables.AspNet perspective it's irrelevant which method you use (GET, POST or any other).

Considering RESTful API pattern, you should be using GET just as it is today. Also considering it's an ajax async background request (thus will not be visible to SEO nor to users) this behavior is considered perfectly fine. Query strings are not recommended for visible (SEO/users) url because they are dificult to read and to index, but that has absolutely no impact on webservices or APIs (which is the case).

You can, however, use POST (or any other method) and avoid query strings but that's not related to DataTables.AspNet (server-side) at all. You have to configure that on request generation (jQuery DataTables plugin itself) and allow your controller to answer that method. All configs related to DataTables.AspNet are kept untouched for that :)

**Comment by TDK1964** [comment]
OK it works now however, is there no support for server side filtering and paging?
I'm using Dapper so was drawn to your dapper extension.

**Comment by ALMMa** [comment]
## Server-side processing
The whole ideia behind this project is to allow server-side processing in a less cumbersome way: by parsing and organizing paging info, filters, sort and more. 

The basic MVC sample works exactly that way. If you run & fiddle it you'll notice that for each page there's a request/response with partial ordered data from the sample collection.

Problem is: `jQuery DataTables` does allow that but **not by default**.

I strongly recommend you to check it's docs on server-side processing and learn how to enable and handle it properly. There are many exciting features you might like.

After enabling server-side processing on `jQuery DataTables`, your `IDataTablesRequest` will get populated with filters, sort and more and will make much more sense.

## DataTables.AspNet.Extensions.DapperExtensions
Might be useful, but remember it's a first alpha release still without unit-testing and others and it's not production-ready yet.

Should work on basic scenarios and probably not on more complex ones, but it's still a work in progress. My idea is to provide some sort of binding (maybe including some fluent-api alternative) to make it even more interesting to use :)

Remember that if you use [Dapper](https://github.com/StackExchange/dapper-dot-net) itself, you might want `DataTables.AspNet.Extensions.AnsiSql` to get plain SQL statements instead of `IPredicate` and others (which are for [DapperExtensions](https://github.com/tmsmith/Dapper-Extensions))

**Comment by TDK1964** [comment]
@ALMMa thanks for the reply but I disagree . Your example only deals with in memory data not data retrieved from a database. Using your sample as a guide (assuming we are just dealing with paging) my code looks like this.

```
var data = _dapperContext.Connection.Query<Model>(@"SELECT * FROM Company");
var filteredData = data.Where(_item => _item.Name.Contains(request.Search.Value));
var dataPage = filteredData.Skip(request.Start).Take(request.Length);
var response = DataTablesResponse.Create(request, data.Count(), filteredData.Count(), dataPage);
return new DataTablesJsonResult(response, JsonRequestBehavior.AllowGet);

```
As you can see there is no way server side paging can happen. The resulting sql will always be "SELECT * FROM Company" when I would have expected something like "SELECT * FROM Company ORDER BY Id OFFSET 1 ROWS FETCH NEXT 10 ROWS ONLY;"

**Comment by ALMMa** [comment]
@TDK1964, you're getting confused because you're mixing up many concepts in a row and from what you're asking (now and previous questions), most of them are rather new for you. 
I'll try to give you a detailed explanation here, but please do understand that all this is becoming far beyond the scope of this project:

## 1. Samples are simplistic (so far)
Samples are simplistic because they assume people arriving here to have some basic undertanding of how `jQuery DataTables`, `HTTP`, server X client-side and their ORM of choice works, and to build and run custom SQL statements.

Samples don't rely on any database (yet) thus I cannot show you how to fully build a custom SQL statement. They will include that when the extension packs become a bit more robust but for now keep in mind that you **HAVE TO** understand how to write SQL statements and use request data (directly from `IDataTablesRequest`) to write your own command.

## 2. IMPORTANT
Before going on, please, remember that extensions (`DataTables.AspNet.Extensions.*`) are very very VERY new and might not work on all cases (might not work at all, to be really honest). It's an alpha-1 and I'm still testing and starting to integrate with some POC code.

## 3. Building some WHERE filters
Currently your filters are on server-side but *after* data retrieval. That's not good enough, I get it.

When you want to filter some data through SQL what do you write? Something similar to (... WHERE ...), correct? So, `connection.Query<SomeClass>("SELECT * FROM sometable");` won't help much and that's where your getting it wrong.

Extensions are there to help you with the `WHERE` clause. Not the full SQL command. Just the `WHERE` clause. You might wanna try this:

    connection.Query<SomeClass>("SELECT * FROM sometable " + request.Columns.GetFilter(true));

**YEAH** that's very simplistic and extremely insecure. **DO NOT DELIVER THAT TO PRODUCTION**. But again, it's a sample. This code should enable you to attach filters (where) into your SQL.

Goal for `Extensions` is to provide a way to bind command and command-parameters to help avoid SQL injection but once again: this is very new and I'm still building them up :)

## 4. Avoid retrieving the whole filtered table and, instead, page that data
Let's take one step further and instead of retrieving every record from the filter (eg: 1000), we're gonna page that data (eg: 20 records per page).

You're expecting to get `SELECT * FROM Company ORDER BY Id OFFSET 1 ROWS FETCH NEXT 10 ROWS ONLY;` out from where?

When you want paged data you **do** page that data. You don't expect it to miraculously come up paged so **DO SEND THAT COMMAND** or you won't get paged data at all!

Now, since paging is rather tricky and each database has it's own way (for instance, some older MSSQL versions are extremely cumbersome for that), I'll show you a very simplistic and version-dependent SQL for MSSQL based on your very own sample:

    connection.Query<SomeClass>("SELECT * FROM sometable " + request.Columns.GetFilter(true) + " ORDER BY 1 OFFSET " + request.Start + " ROWS FETCH NEXT " + request.Length + " ROWS ONLY;");

**WOW!**
That should not only filter your data (as from item 3) but also page that data as you're trying to perform. See the diference here?

My guess is that you're probably mixing this idea here with Linq/IQueryable.

IQueryable allows you to create some sort of "command builder" and only after everything is done, run it and retrieve data. Plain old SQL commands do not. They need to be ready for execution. You have to write your SQL to, simultaneously, page, filter and sort your data before running it.

It would be better if you experiment a bit *without* `DataTables.AspNet` and only after that you wire this project up. That will avoid so many mixed concepts and will point you into the right learning path.

## 5. So, DataTables.AspNet won't build that command for me, right?
Yup, that's right. It won't. 
That's far beyond the scope from this project and that's why Dapper, EntityFramework and many others ORM do exist.
DataTables.AspNet is **not** an ORM and although it might try to spill out some SQL filtering and sorting it will do that in a generic/ansi SQL way and will stop right there.

## 6. You said to NOT use this on production because...
First, as I've said, because `Extensions` are very new and not fully tested.
Second, because you should always avoid direct string concat as on the samples here. They are meant to help you understand the whole idea but they expose your code (and database) to several attacks.

## 7. OK, so, after data retrieval...
If you follow item 4, you'll get a paged data. Let's say, 20 out of 1000 records.
Now you can send it back to `jQuery DataTables`:

    var response = DataTablesResponse.Create(request, data.Count(), data.Count(), data);
    return new DataTablesJsonResult(response, JsonRequestBehavior.AllowGet);

"*Oh, but I need both the filtered and the paged count*"

**AGAIN** do now expect samples to provide a ready to use all porpouse fully integrated and absolute complete code. You have to look into it by yourself, and that requires knowledge outside `DataTables.AspNet`.

Take a look and you'll notice that I'm using the same `data` object, which represents filtered&paged data (20 records). That's to avoid 4 SQL commands here and **they are on you now**. Try using some "SELECT COUNT" statement.

Remember that with wither `Dapper` or `DapperExtensions` you can run multiple SQL statements in a single round-trip. Take a look into that, so you can count your database records, count filtered records and count paged data.

## 8. Conclusion
First, before every single question, remember that this project is not meant to deliver database filter, database order, database-anything. It's related to parsing request parameters and writing response data **ONLY**. So, if you're getting confused about how to retrieve data, that's not related to `DataTables.AspNet`.

Second, this project requires some understanding of HTTP, jQuery DataTables, request/response and if you decide to use `Extensions`, some SQL (and maybe Dapper and DapperExtensions too). This project exists to help **you** write those commands up. **NOT** to do that for you.

Third, since this is so far beyond `DataTables.AspNet` scope, I'll close this issue and mark it as question. I won't keep unecessary tickets open.

Fourth, as I've said, you should give `jQuery DataTables` a try **WITHOUT** `DataTables.AspNet`. There are a few concepts you're still missing and that is getting on your way. Do that, really. It will be far better to understand how `jQuery DataTables` works and how to perform data filters, sort and all. Once it's working, you can wire `DataTables.AspNet` and you'll get a better understanding on what is the goal of this project and how can it help you.
